project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!tutorials/python-notebooks/*.ipynb"
    - "!tutorials/r/gdalcubes.qmd"
    - "!tutorials/r/5-r-geospatial.qmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2024 EDMW Workshop 3B"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/EDMW-EarthData-Workshop-2024
  repo-url: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2024
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.md
        contents:
          - team.md
          - schedule.md
          - setup.qmd
          - section: Orientation
            contents:
            - text: RStudio
              href: content/02-rstudio.qmd
            - text: Earthdata login
              href: content/02-earthdata.md
            - text: Local set-up - R
              href: content/02-local-setup-r.qmd
            - text: Local set-up - Python
              href: content/02-local-setup-python.qmd
            - text: Git-Authentication
              href: content/02-git.md
            - text: Git-JupyterLab
              href: content/02-git-jupyter.md
            - text: Git-RStudio
              href: content/02-git-rstudio.md
          - coc.md
      - section: "Tutorials"
        contents:
          - section: "Welcome"
            contents:
              - text: Welcome
                href: content/01-welcome.md
              - text: Geoscience cloud tools
                href: content/01-intro-to-cloud.qmd
              - text: Jupyter hubs
                href: content/01-intro-to-jupyterhub.qmd
          - section: "Tutorials in R"
            contents:
              - text: Search
                href: tutorials/r/1-earthdatalogin.qmd
              - text: Subset and Crop
                href: tutorials/r/2-subset-and-plot.qmd
              - text: Mask to a shapefile
                href: tutorials/r/3-extract-satellite-data-within-boundary.qmd
          - section: "Tutorials in Python"
            contents:
              - text: Search
                href: tutorials/python/1-earthaccess.ipynb
              - text: Subset and Crop
                href: tutorials/python/2-subset-and-plot.ipynb
              - text: Mask to a shapefile
                href: tutorials/python/3-extract-satellite-data-within-boundary.ipynb
              - text: Monthly and seasonal means
                href: tutorials/python/4-data-cubes.ipynb
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://dhub.opensci.live/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2024/discussions
        text: "Discussions"
      - icon: github
        href: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2024
        text: "Repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
